# Generated by Django 6.0.4 on 2026-05-02 09:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending_payment', 'Pending Payment'), ('documents_pending', 'Documents Pending'), ('processing', 'Processing'), ('query_raised', 'Query Raised'), ('review', 'Review'), ('completed', 'Completed')], default='pending_payment', max_length=50)),
                ('financial_year', models.CharField(choices=[('FY2024-25', 'FY 2024-25'), ('FY2025-26', 'FY 2025-26')], default='FY2024-25', max_length=20)),
                ('entity_type', models.CharField(choices=[('individual', 'Individual'), ('nri', 'NRI'), ('partnership', 'Partnership'), ('pvt_ltd', 'Pvt Ltd'), ('public_ltd', 'Public Ltd'), ('trust_aop_boi', 'Trust-AOP-BOI')], default='individual', max_length=50)),
                ('income_types', models.JSONField(default=list)),
                ('original_or_revised', models.CharField(choices=[('original', 'Original'), ('revised', 'Revised')], default='original', max_length=20)),
                ('it_portal_upload_consent', models.BooleanField(default=False)),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_applied', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_orders', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='orders', to='plans.serviceplan')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('gpay', 'Google Pay'), ('bank_transfer', 'Bank Transfer')], default='gpay', max_length=50)),
                ('utr_number', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending Verification'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=50)),
                ('proof_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='orders.workorder')),
            ],
        ),
    ]
