# Generated by Django 6.0.4 on 2026-05-02 09:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uploader_role', models.CharField(choices=[('client', 'Client'), ('staff', 'Staff'), ('owner', 'Owner')], max_length=20)),
                ('document_category', models.CharField(choices=[('salary', 'Salary'), ('house_property', 'House Property'), ('other_sources', 'Other Sources'), ('capital_gains', 'Capital Gains'), ('nri', 'NRI'), ('presumptive_business', 'Presumptive Business'), ('regular_business', 'Regular Business'), ('delivery', 'Delivery'), ('consent', 'Consent'), ('other', 'Other')], max_length=50)),
                ('document_type', models.CharField(max_length=100)),
                ('file_name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='documents/%Y/%m/%d/')),
                ('file_size_kb', models.IntegerField(default=0)),
                ('is_delivery_document', models.BooleanField(default=False)),
                ('version', models.IntegerField(default=1)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='orders.workorder')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
